language: java
deploy:
  provider: heroku
  api_key:
      secure: "g6xF6S2sjxE7WWCM46G/M62Z6uufCVS0+Hqg1135L5mBRaVam4A+teELEBcsTKm5nOKVs
MioguIi9yDepg524HcgnDX5TYFJIiOB+QFdDREdgc9OSm+aD6i7sfbHP9oru9JKHUAPy3CmItD0UwbbO
Rp/fIktl50SD2AXRMXk2nkEp2vtowe2t0jBT0oN/AwZtY/kDu2jEpB+O9C2v62LtfYnARlS0+YJiTlug
5POMQuzwEvgG5BRoO0FYQVJyQ8hsghY/gQPLK9drgQdGNKetC/eLGzg1yzSySwYbcH/qP8V5qqkunLo/
P5sch9rn8bkPHIUb9JRhilMeSWXEEmnfAoLEy4qPBwiOZl2YD8akzEdnFrMKiAW44U2Rhwf4z2RWcG18
TQCj2UpP2HxEvolwgDf1lH7fAAdmKkXtFONi7MlbQzeQWNyeg7O8gjABnSZ+z41oL3vMHSSI65bFRDh5
1Po2gsy3jUQYbKAFDFtqOnMTkbP0r67IMKbxobkXCutuxpTQTm5yunQQvKlA7Iu/3s+Qj6Odri0FlNIa
wePuuChHXULMmF2hjfDgrinIVGPkTcZuUC/DohKH+fTShscc4QRWgoP57oZ5RB94J+4j+90Kwx4GdODp
mtpQuN1o54Bx3imuUA5Si3LFxQEws4VRHp1H4fWsSx659xB2ayejzM="

